#!/bin/sh
#
# If /etc/network/rules.ferm exists, reload it
# before an interface goes up.
#

set -e

if [ ! -x /usr/bin/ferm ]; then
    exit 0
fi

run_ferm () {
    if [ "$VERBOSITY" = "1" ]; then
	set -- --verbose "$@"
    fi

    if [ -n "$IF_FERM_FAST" ]; then
	set -- --fast "$@"
    fi

    ferm "$@"
}

if [ -e /etc/network/rules.ferm ]; then
    run_ferm /etc/network/rules.ferm
fi
